# Initial content coming from
# https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    ## The generated types/requests/responses are huge!
    #-   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
    ## Disabled because it compains about additional modules used in testing
    #-   id: name-tests-test
    #    args: ['--django']
    -   id: requirements-txt-fixer
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: file-contents-sorter
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: pretty-format-json
    -   id: sort-simple-yaml

-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    - id: black
      language_version: python3

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: ['--max-line-length=200', '--ignore=F821', '--ignore=E203']

-   repo: https://github.com/pre-commit/pre-commit
    rev: v2.20.0
    hooks:
    -   id: validate_manifest

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.38.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
        additional_dependencies: [types-all, types-attrs]

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0  # or specific git tag
    hooks:
        - id: shfmt

# end
