name: Run Complete Tests

on:
    workflow_call:

jobs:
    full_tests:
        runs-on: ubuntu-latest
        name: NOX test run
        steps:
            - uses: actions/checkout@v3
            - uses: excitedleigh/setup-nox@v2.0.0
            - run: pip install poetry==1.3.1
            - run: nox
# end
